spring:
  application:
    name: "抑郁症专家系统后台"
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/knowledge_graph?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: zeddic
      password: 103552zjf
      hikari:
        #最小空闲连接数量
        minimum-idle: 5
        #从池返回的连接默认自动提交
        auto-commit: true
        #空闲连接最大时间，10秒
        idle-timeout: 10000
        #池中连接的最长生命周期
        max-lifetime: 1800000
        #数据库连接的超时时间
        connection-timeout: 30000
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 103552zjf
logging:
  level:
    org.neo4j: ERROR
    org.springframework.data.neo4j: ERROR
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启驼峰命名转换
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Ztoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
